name: CD Pipeline - Prod Branch

on:
  push:
    branches:
      - prod

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: 1.0.0
  DOCKER_REGISTRY: madara3

jobs:
  # ===============================
  # JOB 1 - SCAN DE SÉCURITÉ
  # ===============================
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Security scan - Vulnerabilities
        run: |
          echo "Scan de sécurité sur prod..."
          docker run --rm aquasec/trivy image ^
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} || exit 0

  # ===============================
  # JOB 2 - DÉPLOIEMENT SUR RUNNER 'runner_prod'
  # ===============================
  deploy:
    needs: security-scan
    runs-on: [self-hosted, runner_prod]
    env:
      IMAGE_NAME: intranet-newdeal
      IMAGE_TAG: 1.0.0
      DOCKER_REGISTRY: madara3

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Pull latest image
        run: |
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Stop existing container
        run: docker stop intranet-app
        continue-on-error: true

      - name: Remove old container
        run: docker rm intranet-app
        continue-on-error: true

      - name: Run new container (exposer sur port 80)
        run: |
          docker run -d \
            -p 80:80 \
            --name intranet-app \
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
